spring.application.name=CartService

server.port=8082

#spring.application.instance-id=${spring.application.name}.${random.value}

eureka.client.service-url.default-zone=http://localhost:8761/eureka


# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# Circuit Breaker Configuration

# Circuit breaker instance name must match @CircuitBreaker(name="")
resilience4j.circuitbreaker.instances.restaurantService.register-health-indicator=true

# percentage of failures allowed before circuit opens
resilience4j.circuitbreaker.instances.restaurantService.failure-rate-threshold=50

# minimum number of requests before circuit breaker evaluates failure rate
resilience4j.circuitbreaker.instances.restaurantService.minimum-number-of-calls=5

# how long circuit breaker stays open before switching to half-open
resilience4j.circuitbreaker.instances.restaurantService.wait-duration-in-open-state=10s

# number of calls allowed in half-open state
resilience4j.circuitbreaker.instances.restaurantService.permitted-number-of-calls-in-half-open-state=3

# size of sliding window
resilience4j.circuitbreaker.instances.restaurantService.sliding-window-size=10

# sliding window type
resilience4j.circuitbreaker.instances.restaurantService.sliding-window-type=COUNT_BASED

# automatic transition from open to half-open
resilience4j.circuitbreaker.instances.restaurantService.automatic-transition-from-open-to-half-open-enabled=true